Linguagem de Programacao I/EcommerceCCO2023/EcommerceCCO2023/Controllers/ClienteController.cs
using EcommerceCCO2023.Models;
using EcommerceCCO2023.Models.Data;
using Microsoft.AspNetCore.Mvc;

namespace EcommerceCCO2023.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult IndexCliente()
        {
            ClienteData data = new ClienteData();
            return View(data.Read());

        }

        public IActionResult Create()
        {
            ClienteData data = new ClienteData();
            ViewBag.Cliente = data.Read();
            return View();
        }
        // Método para exibir a tela de login
        public IActionResult IndexLogin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string email, string senha)
        {
            ClienteData clienteData = new ClienteData();
            Cliente cliente = clienteData.Authenticate(email, senha);

            if (cliente != null)
            {
                // Autenticação bem-sucedida
                return RedirectToAction("Index", "Home"); // Redirecione para a página inicial
            }
            else
            {
                // Autenticação falhou
                ViewBag.ErrorMessage = "Credenciais inválidas. Tente novamente.";
                return View("IndexLogin"); // Ou qualquer outra view que exibe o formulário de login
            }
        }

        [HttpPost]
        public IActionResult Create(Cliente cliente)
        {
            if (cliente.Nome != null)
            {
                ClienteData data = new ClienteData();
                data.Create(cliente);
            }

            return RedirectToAction("IndexCliente");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            ClienteData data = new ClienteData();
            return View(data.Read(id));
        }

        [HttpPost]
        public IActionResult Update(int id, Cliente cliente)
        {
            cliente.IdCliente = id;

            if (cliente.Nome == null)
                return View(cliente);

            ClienteData data = new ClienteData();
            data.Update(cliente);

            return RedirectToAction("IndexCliente");
        }

        public IActionResult Delete(int id)
        {
            ClienteData data = new ClienteData();
            data.Delete(id);

            return RedirectToAction("IndexCliente");
        }
    }
}

Linguagem de Programacao I/EcommerceCCO2023/EcommerceCCO2023/Controllers/ProdutoController.cs
using EcommerceCCO2023.Models;
using EcommerceCCO2023.Models.Data;
using Microsoft.AspNetCore.Mvc;

namespace EcommerceCCO2023.Controllers
{
	public class ProdutoController : Controller
	{
		public IActionResult IndexProd()
		{
			ProdutoData data = new ProdutoData();
			return View(data.Read());

		}

		public IActionResult Create()
		{
			CategoriaData data = new CategoriaData();
			ViewBag.Categorias = data.Read();
			return View();
		}

		[HttpPost]
		public IActionResult Create(Produto prod)
		{
			if (prod.NomeProd != null)
			{
				ProdutoData data = new ProdutoData();
				data.Create(prod);
			}

			return RedirectToAction("IndexProd");
		}

		[HttpGet]
		public IActionResult Update(int id)
		{
			CategoriaData dataCat = new CategoriaData();
			ViewBag.Categorias = dataCat.Read();

			ProdutoData data = new ProdutoData();
			return View(data.Read(id));
		}

		[HttpPost]
		public IActionResult Update(int id, Produto prod)
		{
			prod.IdProduto = id;

			if (prod.NomeProd == null)
				return View(prod);

			ProdutoData data = new ProdutoData();
			data.Update(prod);

			return RedirectToAction("Index", "Home");
		}

		public IActionResult Delete(int id)
		{
			ProdutoData data = new ProdutoData();
			data.Delete(id);

			return RedirectToAction("Index", "Home");
		}
	}
}

Linguagem de Programacao I/EcommerceCCO2023/EcommerceCCO2023/Views/Shared/_Carousel.cshtml
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100 h-100" src="~/images/bmw-series-3.jpg" alt="..." width="100" height="200">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100 h-100" src="~/images/ferrari.jpg" alt="..." width="100" height="200">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100 h-100" src="~/images/bmw-x1.jpg" alt="..." width="100" height="200">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

Linguagem de Programacao I/EcommerceCCO2023/EcommerceCCO2023/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] Linguagem de Programação - UNIRP</title> <!-- foi retirado o bootstrap do link rel, quebrou a aba "produtos"-->
	<link rel="stylesheet" href="~/css/styles.css" />
	<link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
</head>
<body>
	<header class="header" id="header">
		<nav class="nav container">
			<a href="#" class="nav__logo">
				<img src="~/images/logo.png" alt="logo image">
				Sushi
			</a>

			<div class="nav__menu" id="nav-menu">
				<ul class="nav__list">
					<li class="nav__item">
						<a class="nav__link" asp-area="" asp-controller="" asp-action="Index">Home</a>
					</li>

					<li class="nav__item">
						<a class="nav__link" asp-area="" asp-controller="Produto" asp-action="IndexProd">Produto</a> 
					</li>

					<li class="nav__item">
						<a class="nav__link" asp-area="" asp-controller="Cliente" asp-action="IndexCliente">Cliente</a>
					</li>
				</ul>

				<!-- Close Button -->
				<div class="nav__close" id="nav-close">
					<i class="ri-close-line"></i>
				</div>

				<img src="~/images/leaf-branch-4.png" alt="nav image" class="nav__img-1">
				<img src="~/images/leaf-branch-3.png" alt="nav image" class="nav__img-2">
			</div>

			<div class="nav__buttons">
				<!--Theme Change Button-->
				<i class="ri-moon-line change-theme" id="theme-button"></i>

				<!-- Toggle Button-->
				<div class="nav__toggle" id="nav-toggle">
					<i class="ri-apps-2-line"></i>
				</div>
			</div>
		</nav>
	</header>

	<!--==================== MAIN ====================-->
	<main class="main">
		<!--==================== HOME ====================-->
		<section class="home section" id="home">
			<div class="home__container container grid">
				<img src="~/images/home-sushi-rolls.png" alt="home image" class="home__img">

				<div class="home__data">
					<h1 class="home__title">
						Aproveite Deliciosamente

						<div>
							<img src="~/images/home-sushi-title.png" alt="home image">
							Sushi Food
						</div>
					</h1>

					<p class="home__description">
						Aproveite de um bom jantar com os melhores pratos 
						do restaurante e melhore o seu dia.
					</p>

					<a href="#" class="button">
						Peça agora <i class="ri-arrow-right-line"></i>
					</a>
				</div>
			</div>

			<img src="~/images/leaf-branch-2.png" alt="home image" class="home__leaf-1">
			<img src="~/images/leaf-branch-4.png" alt="home image" class="home__leaf-2">
		</section>
		<div class="container">
			<main role="main" class="pb-3">
				@RenderBody()
			</main>
		</div>

		<!--==================== ABOUT ====================-->
		<section class="about section" id="about">
			<div class="about__container container grid">
				<div class="about__data">
					<span class="section__subtitle">Sobre nós</span>
					<h2 class="section__title about__title">
						<div>
							Nós fornecemos
							<img src="~/images/about-sushi-title.png" alt="about image">
						</div>

						Comida saudável
					</h2>

					<p class="about__description">
						A comida nos alcança por meio de nossos parentes, sejam eles alados ou enraizados.
						Da mesma forma que temos raízes genealógicas, a comida também tem uma cultura, 
						uma história que atravessa gerações.
					</p>
				</div>

				<img src="~/images/about-sushi.png" alt="about image" class="about__img">
			</div>

			<img src="~/images/leaf-branch-1.png" alt="about image" class="about__leaf">
		</section>
	</main>
	</header>


	<footer class="footer">
		<div class="footer__container container grid">
			<div>
				<a href="#" class="footer__logo">
					<img src="~/images/logo.png" alt="logo image">
					Sushi
				</a>


				<p class="footer__description">
					Alimento para o corpo não é <br>
					suficiente. Deve ter comida <br>
					para a alma.
				</p>
			</div>

			<div class="footer__content">
				<div>
					<h3 class="footer__title">Principal</h3>

					<ul class="footer__links">
						<li>
							<a href="#" class="footer__link">Sobre</a>
						</li>

						<li>
							<a href="#" class="footer__link">Menu</a>
						</li>

						<li>
							<a href="#" class="footer__link">Mostrar</a>
						</li>

						<li>
							<a href="#" class="footer__link">Eventos</a>
						</li>
					</ul>
				</div>

				<div>
					<h3 class="footer__title">Informações</h3>

					<ul class="footer__links">
						<li>
							<a href="#" class="footer__link">Contato</a>
						</li>

						<li>
							<a href="#" class="footer__link">Pedidos</a>
						</li>

						<li>
							<a href="#" class="footer__link">Videos</a>
						</li>

						<li>
							<a href="#" class="footer__link">Reservas</a>
						</li>
					</ul>
				</div>

				<div>
					<h3 class="footer__title">Endereço</h3>

					<ul class="footer__links">
						<li class="footer__information">
							Av. Hacienda 1234 <br>
							Lima 4321, Peru
						</li>

						<li class="footer__information">
							9:00 - 23:00
						</li>
					</ul>
				</div>

				<div>
					<h3 class="footer__title">Redes Sociais</h3>

					<ul class="footer__social">
						<a href="https://www.facebook.com/" target="_blank" class="footer__social-link">
							<i class="ri-facebook-circle-fill"></i>
						</a>

						<a href="https://www.instagram.com/" target="_blank" class="footer__social-link">
							<i class="ri-instagram-fill"></i>
						</a>

						<a href="https://www.twitter.com/" target="_blank" class="footer__social-link">
							<i class="ri-twitter-fill"></i>
						</a>
					</ul>
				</div>
			</div>

			<img src="~/images/spring-onion.png" alt="footer image" class="footer__onion">
			<img src="~/images/spinach-leaf.png" alt="footer image" class="footer__spinach">
			<img src="~/images/leaf-branch-4.png" alt="footer image" class="footer__leaf">
		</div>

		<div class="footer__info container">
			<div class="footer__card">
				<img src="~/images/footer-card-1.png" alt="footer image">
				<img src="~/images/footer-card-2.png" alt="footer image">
				<img src="~/images/footer-card-3.png" alt="footer image">
				<img src="~/images/footer-card-4.png" alt="footer image">
			</div>

			<span class="footer__copy">
				&#169; Copyright I DO Systems. All rights reserved
			</span>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/notify.min.js" asp-append-version="true"></script>
	<script src="~/js/main.js" asp-append-version="true"></script>
	<script src="https://unpkg.com/scrollreveal"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>

Linguagem de Programacao I/EcommerceCCO2023/EcommerceCCO2023/Views/Shared/_LayoutCliente.cshtml
<!-- este arquivo foi criado para dar layout a tela de produtos incluindo paginação-->

<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] Linguagem de Programação - UNIRP</title> <!-- foi retirado o bootstrap do link rel, quebrou a aba "produtos"-->
	<link rel="stylesheet" href="~/css/styles.css" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
</head>
<body>
	<header class="header" id="header">
		<nav class="nav container">
			<a href="#" class="nav__logo">
				<img src="~/images/logo.png" alt="logo image">
				Sushi
			</a>

			<div class="nav__menu" id="nav-menu">
				<ul class="nav__list">
					<li class="nav__item">
						<a class="nav__link" asp-area="" asp-controller="" asp-action="Index">Home</a>
					</li>

					<li class="nav__item">
						<a class="nav__link" asp-area="" asp-controller="Produto" asp-action="IndexProd">Produto</a> 
					</li>
					<li class="nav__item">
						<a class="nav__link" asp-area="" asp-controller="Cliente" asp-action="IndexCliente">Cliente</a>
					</li>
				</ul>

				<!-- Close Button -->
				<div class="nav__close" id="nav-close">
					<i class="ri-close-line"></i>
				</div>

				<img src="~/images/leaf-branch-4.png" alt="nav image" class="nav__img-1">
				<img src="~/images/leaf-branch-3.png" alt="nav image" class="nav__img-2">
			</div>

			<div class="nav__buttons">
				<!--Theme Change Button-->
				<i class="ri-moon-line change-theme" id="theme-button"></i>

				<!-- Toggle Button-->
				<div class="nav__toggle" id="nav-toggle">
					<i class="ri-apps-2-line"></i>
				</div>
			</div>
		</nav>
	</header>

	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="footer">
		<div class="footer__container container grid">
			<div>
				<a href="#" class="footer__logo">
					<img src="~/images/logo.png" alt="logo image">
					Sushi
				</a>


				<p class="footer__description">
					Alimento para o corpo não é <br>
					suficiente. Deve ter comida <br>
					para a alma.
				</p>
			</div>

			<div class="footer__content">
				<div>
					<h3 class="footer__title">Principal</h3>

					<ul class="footer__links">
						<li>
							<a href="#" class="footer__link">Sobre</a>
						</li>

						<li>
							<a href="#" class="footer__link">Menu</a>
						</li>

						<li>
							<a href="#" class="footer__link">Mostrar</a>
						</li>

						<li>
							<a href="#" class="footer__link">Eventos</a>
						</li>
					</ul>
				</div>

				<div>
					<h3 class="footer__title">Informações</h3>

					<ul class="footer__links">
						<li>
							<a href="#" class="footer__link">Contato</a>
						</li>

						<li>
							<a href="#" class="footer__link">Pedidos</a>
						</li>

						<li>
							<a href="#" class="footer__link">Videos</a>
						</li>

						<li>
							<a href="#" class="footer__link">Reservas</a>
						</li>
					</ul>
				</div>

				<div>
					<h3 class="footer__title">Endereço</h3>

					<ul class="footer__links">
						<li class="footer__information">
							Av. Hacienda 1234 <br>
							Lima 4321, Peru
						</li>

						<li class="footer__information">
							9:00 - 23:00
						</li>
					</ul>
				</div>

				<div>
					<h3 class="footer__title">Redes Sociais</h3>

					<ul class="footer__social">
						<a href="https://www.facebook.com/" target="_blank" class="footer__social-link">
							<i class="ri-facebook-circle-fill"></i>
						</a>

						<a href="https://www.instagram.com/" target="_blank" class="footer__social-link">
							<i class="ri-instagram-fill"></i>
						</a>

						<a href="https://www.twitter.com/" target="_blank" class="footer__social-link">
							<i class="ri-twitter-fill"></i>
						</a>
					</ul>
				</div>
			</div>

			<img src="~/images/spring-onion.png" alt="footer image" class="footer__onion">
			<img src="~/images/spinach-leaf.png" alt="footer image" class="footer__spinach">
			<img src="~/images/leaf-branch-4.png" alt="footer image" class="footer__leaf">
		</div>

		<div class="footer__info container">
			<div class="footer__card">
				<img src="~/images/footer-card-1.png" alt="footer image">
				<img src="~/images/footer-card-2.png" alt="footer image">
				<img src="~/images/footer-card-3.png" alt="footer image">
				<img src="~/images/footer-card-4.png" alt="footer image">
			</div>

			<span class="footer__copy">
				&#169; Copyright I DO Systems. All rights reserved
			</span>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/main.js" asp-append-version="true"></script>
	<script src="https://unpkg.com/scrollreveal"></script>
</body>
</html>

Linguagem de Programacao I/EcommerceCCO2023/EcommerceCCO2023/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] Linguagem de Programação - UNIRP</title> <!-- foi retirado o bootstrap do link rel, quebrou a aba "produtos"-->
	<link rel="stylesheet" href="~/css/styles.css" />
	<link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
</head>
<body>
	<header class="header" id="header">
		<nav class="nav container">
			<a href="#" class="nav__logo">
				<img src="~/images/logo.png" alt="logo image">
				Sushi
			</a>

			<div class="nav__menu" id="nav-menu">
				<ul class="nav__list">
					<li class="nav__item">
						<a class="nav__link" asp-area="" asp-controller="" asp-action="Index">Home</a>
					</li>

					<li class="nav__item">
						<a class="nav__link" asp-area="" asp-controller="Produto" asp-action="IndexProd">Produto</a> 
					</li>

					<li class="nav__item">
						<a class="nav__link" asp-area="" asp-controller="Cliente" asp-action="IndexCliente">Cliente</a>
					</li>
				</ul>

				<!-- Close Button -->
				<div class="nav__close" id="nav-close">
					<i class="ri-close-line"></i>
				</div>

				<img src="~/images/leaf-branch-4.png" alt="nav image" class="nav__img-1">
				<img src="~/images/leaf-branch-3.png" alt="nav image" class="nav__img-2">
			</div>

			<div class="nav__buttons">
				<!--Theme Change Button-->
				<i class="ri-moon-line change-theme" id="theme-button"></i>

				<!--User login Button-->
				<i class="ri-user-line" id="user-button"></i>

				<!-- Toggle Button-->
				<div class="nav__toggle" id="nav-toggle">
					<i class="ri-apps-2-line"></i>
				</div>
			</div>
		</nav>
	</header>

	<!--==================== MAIN ====================-->
	<main class="main">
		<!--==================== HOME ====================-->
		<section class="home section" id="home">
			<div class="home__container container grid">
				<img src="~/images/home-sushi-rolls.png" alt="home image" class="home__img">

				<div class="home__data">
					<h1 class="home__title">
						Aproveite Deliciosamente

						<div>
							<img src="~/images/home-sushi-title.png" alt="home image">
							Sushi Food
						</div>
					</h1>

					<p class="home__description">
						Aproveite de um bom jantar com os melhores pratos 
						do restaurante e melhore o seu dia.
					</p>

					<a href="#" class="button">
						Peça agora <i class="ri-arrow-right-line"></i>
					</a>
				</div>
			</div>

			<img src="~/images/leaf-branch-2.png" alt="home image" class="home__leaf-1">
			<img src="~/images/leaf-branch-4.png" alt="home image" class="home__leaf-2">
		</section>
		<div class="container">
			<main role="main" class="pb-3">
				@RenderBody()
			</main>
		</div>

		<!--==================== ABOUT ====================-->
		<section class="about section" id="about">
			<div class="about__container container grid">
				<div class="about__data">
					<span class="section__subtitle">Sobre nós</span>
					<h2 class="section__title about__title">
						<div>
							Nós fornecemos
							<img src="~/images/about-sushi-title.png" alt="about image">
						</div>

						Comida saudável
					</h2>

					<p class="about__description">
						A comida nos alcança por meio de nossos parentes, sejam eles alados ou enraizados.
						Da mesma forma que temos raízes genealógicas, a comida também tem uma cultura, 
						uma história que atravessa gerações.
					</p>
				</div>

				<img src="~/images/about-sushi.png" alt="about image" class="about__img">
			</div>

			<img src="~/images/leaf-branch-1.png" alt="about image" class="about__leaf">
		</section>
	</main>
	</header>


	<footer class="footer">
		<div class="footer__container container grid">
			<div>
				<a href="#" class="footer__logo">
					<img src="~/images/logo.png" alt="logo image">
					Sushi
				</a>


				<p class="footer__description">
					Alimento para o corpo não é <br>
					suficiente. Deve ter comida <br>
					para a alma.
				</p>
			</div>

			<div class="footer__content">
				<div>
					<h3 class="footer__title">Principal</h3>

					<ul class="footer__links">
						<li>
							<a href="#" class="footer__link">Sobre</a>
						</li>

						<li>
							<a href="#" class="footer__link">Menu</a>
						</li>

						<li>
							<a href="#" class="footer__link">Mostrar</a>
						</li>

						<li>
							<a href="#" class="footer__link">Eventos</a>
						</li>
					</ul>
				</div>

				<div>
					<h3 class="footer__title">Informações</h3>

					<ul class="footer__links">
						<li>
							<a href="#" class="footer__link">Contato</a>
						</li>

						<li>
							<a href="#" class="footer__link">Pedidos</a>
						</li>

						<li>
							<a href="#" class="footer__link">Videos</a>
						</li>

						<li>
							<a href="#" class="footer__link">Reservas</a>
						</li>
					</ul>
				</div>

				<div>
					<h3 class="footer__title">Endereço</h3>

					<ul class="footer__links">
						<li class="footer__information">
							Av. Hacienda 1234 <br>
							Lima 4321, Peru
						</li>

						<li class="footer__information">
							9:00 - 23:00
						</li>
					</ul>
				</div>

				<div>
					<h3 class="footer__title">Redes Sociais</h3>

					<ul class="footer__social">
						<a href="https://www.facebook.com/" target="_blank" class="footer__social-link">
							<i class="ri-facebook-circle-fill"></i>
						</a>

						<a href="https://www.instagram.com/" target="_blank" class="footer__social-link">
							<i class="ri-instagram-fill"></i>
						</a>

						<a href="https://www.twitter.com/" target="_blank" class="footer__social-link">
							<i class="ri-twitter-fill"></i>
						</a>
					</ul>
				</div>
			</div>

			<img src="~/images/spring-onion.png" alt="footer image" class="footer__onion">
			<img src="~/images/spinach-leaf.png" alt="footer image" class="footer__spinach">
			<img src="~/images/leaf-branch-4.png" alt="footer image" class="footer__leaf">
		</div>

		<div class="footer__info container">
			<div class="footer__card">
				<img src="~/images/footer-card-1.png" alt="footer image">
				<img src="~/images/footer-card-2.png" alt="footer image">
				<img src="~/images/footer-card-3.png" alt="footer image">
				<img src="~/images/footer-card-4.png" alt="footer image">
			</div>

			<span class="footer__copy">
				&#169; Copyright I DO Systems. All rights reserved
			</span>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/notify.min.js" asp-append-version="true"></script>
	<script src="~/js/main.js" asp-append-version="true"></script>
	<script src="https://unpkg.com/scrollreveal"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>

Linguagem de Programacao I/EcommerceCCO2023/EcommerceCCO2023/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] Linguagem de Programação - UNIRP</title>
    <link rel="stylesheet" href="~/css/login.css" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>

<body>

    <div class="wrapper">
        <h1>Login</h1>

        <form method="post" action="@Url.Action("Login", "Cliente")">
            <div class="imput-box">
                <input type="text" name="Email" placeholder="E-mail" required>
                <i class='bx bxs-user'></i>
            </div>
            <div class="imput-box">
                <input type="password" name="Senha" placeholder="Senha" required>
                <i class='bx bxs-lock-alt'></i>
            </div>

            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <div class="remember-forgot">
                <label><input type="checkbox"> Mostrar senha </label>
                <a href="#">Esqueci minha senha</a>
            </div>

            <button type="submit" class="btn">Login</button>
        </form>

        <div class="register-link">
            <p>Não tem Login? <a href="#">Register</a></p>
        </div>
    </div>

    @RenderSection("Scripts", required: false)
</body>

</html>

Linguagem de Programacao I/EcommerceCCO2023/EcommerceCCO2023/Views/Shared/_ProdutoResumo.cshtml
@model Produto
<!-- Criando duas colunas de tamanho 6 que podem funcionar em
                3 tipos de dispositivos: peq., med., grd -->

<section class="popular section" id="popular">

    <article class="popular__card">
        <p><img src="~/images/@Model.UrlImagem" alt = "@Model.UrlImagem" class="popular__img"></p>
        <h3>Preço: @Model.Valor.ToString("c")</h3>

        <!-- Nome do lanche é link para mostrar a descrição detalhado do Lanche -->
        <a asp-controller="Lanche" asp-action="Details"
            asp-route-lancheId="@Model.IdProduto">
            @Model.NomeProd
        </a>

        <p>@Model.Descricao</p>

        <!-- Botão para adicionar o lanche selecionado ao Carrinho de Compra -->
        <button class="popular__button">
                <a class="btn btn-primary" id="carButton"
                    asp-controller="CarrinhoCompra"
                    asp-action="AdicionarItemAoCarrinhoCompra"
                    asp-route-LancheId="@Model.IdProduto">
                    <i class = "ri-shopping-bag-line"></i>
                </a>
        </button>
    </article>
</section>